openapi: '3.0.1'
info:
  title: 'Vocably API'
  version: '1.0.0'
paths:
  /translate:
    post:
      operationId: 'translate'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Phrase'
        required: true
      responses:
        '200':
          description: '200 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Translation'
      security:
        - jwt-authorizer: []
      x-amazon-apigateway-request-validator: 'all'
      x-amazon-apigateway-integration:
        payloadFormatVersion: '2.0'
        type: 'aws_proxy'
        httpMethod: 'POST'
        uri: '${translateLambdaInvokeArn}'
        connectionType: 'INTERNET'
components:
  schemas:
    LexicalaSearchResultItem:
      type: object
      properties:
        id:
          type: string
        language:
          type: string
        headword:
          type: object
          properties:
            text:
              type: string
            pos:
              type: string
        senses:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              definition:
                type: string
      required:
        - id
        - language
        - headword
        - senses
    Translation:
      type: object
      properties:
        language:
          type: string
        text:
          type: string
        lexicala:
          type: array
          items:
            $ref: '#/components/schemas/LexicalaSearchResultItem'
      required:
        - language
        - text
        - cards
    Phrase:
      type: object
      properties:
        phrase:
          type: string
        language:
          type: string
      required:
        - phrase
  securitySchemes:
    jwt-authorizer:
      type: 'oauth2'
      flows: {}
      x-amazon-apigateway-authorizer:
        identitySource: '$request.header.Authorization'
        jwtConfiguration:
          audience:
            - '${authClientId}'
          issuer: 'https://cognito-idp.$${AWS::Region}.amazonaws.com/${userPoolId}'
        type: 'jwt'
x-amazon-apigateway-request-validators:
  all:
    validateRequestParameters: true
    validateRequestBody: true
