openapi: '3.0.1'
info:
  title: 'Vocably API'
  version: '1.0.0'
paths:
  /translate:
    post:
      operationId: 'translate'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Phrase'
        required: true
      responses:
        '200':
          description: '200 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Translation'
      security:
        - jwt-authorizer: []
      x-amazon-apigateway-request-validator: 'all'
      x-amazon-apigateway-integration:
        payloadFormatVersion: '2.0'
        type: 'aws_proxy'
        httpMethod: 'POST'
        uri: '${translateLambdaInvokeArn}'
        connectionType: 'INTERNET'
components:
  schemas:
    Translation:
      type: 'object'
      properties:
        asIs:
          type: 'string'
    Phrase:
      type: 'object'
      properties:
        phrase:
          type: 'string'
  securitySchemes:
    jwt-authorizer:
      type: 'oauth2'
      flows: {}
      x-amazon-apigateway-authorizer:
        identitySource: '$request.header.Authorization'
        jwtConfiguration:
          audience:
            - '${authClientId}'
          issuer: 'https://cognito-idp.$${AWS::Region}.amazonaws.com/${userPoolId}'
        type: 'jwt'
x-amazon-apigateway-request-validators:
  all:
    validateRequestParameters: true
    validateRequestBody: true
