openapi: '3.0.1'
info:
  title: 'Vocably API'
  version: '1.0.0'
paths:
  /translate:
    post:
      operationId: 'translate'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Phrase'
        required: true
      responses:
        '200':
          description: '200 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Translation'
      security:
        - UserPool: []
      x-amazon-apigateway-request-validator: 'all'
      x-amazon-apigateway-integration:
        httpMethod: 'POST'
        uri: 'arn:$${AWS::Partition}:apigateway:$${AWS::Region}:lambda:path/2015-03-31/functions/${translateLambdaArn}/invocations'
        passthroughBehavior: 'when_no_match'
        type: 'aws_proxy'
components:
  schemas:
    Translation:
      type: 'object'
      properties:
        asIs:
          type: 'string'
    Phrase:
      type: 'object'
      properties:
        phrase:
          type: 'string'
  securitySchemes:
    UserPool:
      type: 'apiKey'
      name: 'Authorization'
      in: 'header'
      x-amazon-apigateway-authtype: 'cognito_user_pools'
      x-amazon-apigateway-authorizer:
        providerARNs:
          - '${userPoolArn}'
        type: 'cognito_user_pools'
x-amazon-apigateway-request-validators:
  all:
    validateRequestParameters: true
    validateRequestBody: true
